name: Ci-Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        target: 
          - aarch64-linux-android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        # 回归最新的 stable 编译器，解决 1.78 版本依赖限制
        run: rustup update stable
        
      - name: Setup Cache
        uses: Swatinem/rust-cache@v2  
        
      - name: Get version
        id: get-version
        run: |
          echo "version=$(rustc --version)" >> $GITHUB_OUTPUT
        shell: bash
        
      - name: Install cargo ndk
        # 核心修复：加上 --locked 强制锁死当年发布时的依赖版本，不让它乱下载最新依赖
        run: cargo install cargo-ndk --version 3.8.1 --locked
        shell: bash  
        
      - name: Install target
        run: rustup target add ${{matrix.target}}
        
      - name: build
        run: cargo ndk -t ${{matrix.target}} build --profile githubci 
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mtbinloader2-${{ matrix.target }}
          path: target/${{ matrix.target }}/githubci/libmtbinloader2.so
