name: Android CI

on:
  workflow_dispatch: # 允许你在网页上手动点击运行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-linux-android

    - name: Install Android NDK
      run: |
        echo "y" | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "ndk;25.2.9519653"
        echo "ANDROID_NDK_ROOT=${ANDROID_HOME}/ndk/25.2.9519653" >> $GITHUB_ENV

    - name: Build SO Library
      run: |
        # 使用 NDK 提供的链接器进行交叉编译
        export CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang
        cargo build --target aarch64-linux-android --release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: mtbinloader2-so
        path: target/aarch64-linux-android/release/*.so
